In [1]:
import numpy as np
demo_array = np.arange(10,21)
subset_demo_array = demo_array[0:7]
subset_demo_array[:]= 101
subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [2]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [3]:
test_array = np.array([1,2,3,4,5,6,7,8,9,10])
bool = test_array > 5
bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [5]:
array = array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29])
array.reshape(10,3)

NameError: name 'array' is not defined

In [7]:
def edit_col(col):
    col = col*2 + 10
  return col

df.malic_acid.apply(edit_col)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)

In [8]:
df['alcalinity_of_ash'].mean()

NameError: name 'df' is not defined